### ISSUE TITLE
Prerequisite Hardware Links broken

### ISSUE THREAD

**Issue by codegamc** [brannondorsey/chattervox#22]
The link to the BTech cable is broken.[ New Link to similar product.](https://www.amazon.com/BTECH-APRS-K1-Interface-APRSDroid-Compatible/dp/B01LMIBAZW/ref=sr_1_2?ie=UTF8&qid=1550509206&sr=8-2&keywords=APRS+Cable)

The link to the DIY cable ("zine") is password-protected, and cannot be accessed.

**Comment by brannondorsey** [comment]
I've updated the BTech link to point to BTech's product page and linked to a new Archive.org link for the Zine. Props to @Famicoman for putting that on the Archive just in time!

Thanks @codegamc for bringing these issues to my attention.
